# conda env create -f environment.yml
name: teamcaptain
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - requests
  - selenium
  - beautifulsoup4
  - webdriver-manager
  - lxml
  - numpy
  - pandas
  - penpyxl
  - gitpython
  - psutil